In [36]:
import gym
import numpy as np
import time, pickle, os

env = gym.make('FrozenLake-v0')

epsilon = 0.9
total_episodes = 10000
max_steps = 100

lr_rate = 0.81
gamma = 0.96

actions_dict = {
    '0': 'Esquerda',
    '1': 'Baixo',
    '2': 'Direita', 
    '3': 'Cima'
}

Q = np.zeros((env.observation_space.n, env.action_space.n))
    
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def learn(state, state2, reward, action):
    predict = Q[state, action]
    target = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = Q[state, action] + lr_rate * (target - predict)

# Start
for episode in range(total_episodes):
    state = env.reset()
    t = 0
    
    while t < max_steps:
        

        action = choose_action(state)  
        if episode == total_episodes-1:
            print("Estado Antes")
            env.render()
            print("Acao a ser tomada: " + actions_dict[str(action)])

        state2, reward, done, info = env.step(action)  
        learn(state, state2, reward, action)
        state = state2
        if episode == total_episodes-1:
            print("Estado Apos")
            env.render()
            #print(action)
            print("------------------")


        t += 1
       
        if done:
            break
    if episode == total_episodes-1:
        print("=========End of Episode============")

        #time.sleep(0.1)

print(Q)

Estado Antes

SFFF
FHFH
FFFH
HFFG
Acao a ser tomada: Baixo
Estado Apos
  (Down)
SFFF
FHFH
FFFH
HFFG
------------------
Estado Antes
  (Down)
SFFF
FHFH
FFFH
HFFG
Acao a ser tomada: Baixo
Estado Apos
  (Down)
SFFF
FHFH
FFFH
HFFG
------------------
Estado Antes
  (Down)
SFFF
FHFH
FFFH
HFFG
Acao a ser tomada: Direita
Estado Apos
  (Right)
SFFF
FHFH
FFFH
HFFG
------------------
Estado Antes
  (Right)
SFFF
FHFH
FFFH
HFFG
Acao a ser tomada: Cima
Estado Apos
  (Up)
SFFF
FHFH
FFFH
HFFG
------------------
Estado Antes
  (Up)
SFFF
FHFH
FFFH
HFFG
Acao a ser tomada: Cima
Estado Apos
  (Up)
SFFF
FHFH
FFFH
HFFG
------------------
=========End of Episode============
[[0.58248369 0.58776373 0.61519812 0.63164821]
 [0.59079135 0.66241551 0.5071474  0.64719399]
 [0.7121251  0.69914721 0.67728636 0.65790083]
 [0.47188825 0.55567724 0.10607004 0.58086908]
 [0.60196274 0.4682203  0.56617066 0.1080803 ]
 [0.         0.         0.         0.        ]
 [0.09520221 0.14202224 0.13276858 0.09865072]
 [0.        